apiVersion: v1
kind: PersistentVolume
metadata:
  name: morse-app-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ramon3/stmp/persistent-volumes-rancher/morse-app-pv"