apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "flask-morse-app.labels" . | nindent 4 }}
  name: {{ include "flask-morse-app.fullname" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetport }}
  selector:
    {{- include "flask-morse-app.selectorLabels" . | nindent 4 }}
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.loadbalancerip }}
  type: {{ .Values.service.type }}